//! Per-language tree-sitter `LangSpec` definitions.

// tier 1
#[cfg(feature = "lang-typescript")]
pub mod typescript;
#[cfg(feature = "lang-javascript")]
pub mod javascript;
#[cfg(feature = "lang-python")]
pub mod python;
#[cfg(feature = "lang-go")]
pub mod go;
#[cfg(feature = "lang-rust")]
pub mod rust_lang;
#[cfg(feature = "lang-java")]
pub mod java;
#[cfg(feature = "lang-ruby")]
pub mod ruby;
#[cfg(feature = "lang-php")]
pub mod php;
#[cfg(feature = "lang-c")]
pub mod c;
#[cfg(feature = "lang-cpp")]
pub mod cpp;
#[cfg(feature = "lang-csharp")]
pub mod csharp;

// tier 2
#[cfg(feature = "lang-bash")]
pub mod bash;
#[cfg(feature = "lang-lua")]
pub mod lua;
#[cfg(feature = "lang-zig")]
pub mod zig;
#[cfg(feature = "lang-dart")]
pub mod dart;
#[cfg(feature = "lang-swift")]
pub mod swift;
#[cfg(feature = "lang-scala")]
pub mod scala;
#[cfg(feature = "lang-haskell")]
pub mod haskell;
#[cfg(feature = "lang-ocaml")]
pub mod ocaml;
#[cfg(feature = "lang-elixir")]
pub mod elixir;
#[cfg(feature = "lang-erlang")]
pub mod erlang;
#[cfg(feature = "lang-elm")]
pub mod elm;
#[cfg(feature = "lang-julia")]
pub mod julia;
#[cfg(feature = "lang-scheme")]
pub mod scheme;
#[cfg(feature = "lang-solidity")]
pub mod solidity;
#[cfg(feature = "lang-perl")]
pub mod perl;
#[cfg(feature = "lang-fortran")]
pub mod fortran;
#[cfg(feature = "lang-d")]
pub mod d;
#[cfg(feature = "lang-fsharp")]
pub mod fsharp;
#[cfg(feature = "lang-groovy")]
pub mod groovy;
#[cfg(feature = "lang-objc")]
pub mod objc;
#[cfg(feature = "lang-cuda")]
pub mod cuda;
#[cfg(feature = "lang-glsl")]
pub mod glsl;
#[cfg(feature = "lang-hlsl")]
pub mod hlsl;
#[cfg(feature = "lang-verilog")]
pub mod verilog;
#[cfg(feature = "lang-vhdl")]
pub mod vhdl;
#[cfg(feature = "lang-cmake")]
pub mod cmake;
#[cfg(feature = "lang-make")]
pub mod make;
#[cfg(feature = "lang-nix")]
pub mod nix;
#[cfg(feature = "lang-vim")]
pub mod vim;
#[cfg(feature = "lang-fish")]
pub mod fish;
#[cfg(feature = "lang-jq")]
pub mod jq;
#[cfg(feature = "lang-hcl")]
pub mod hcl;
